spring:
  datasource:
    url: jdbc:h2:mem:Monew;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS public
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  batch:
    job:
      enabled: false
    notification-cleanup:
      cron: "0 0 0 * * ?"
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
      platform: h2